### PR TITLE
fix(eslint-plugin): add missing rule exports

### LINKED ISSUE #49: Add missing rules to index
The following rules have already been completed but are missing from the index:

- directive-class-suffix
- no-forward-ref
- relative-url-prefix
- use-injectable-provided-in

I will add these and update the readme.

### PR DESCRIPTION
**Pull request by nzacca**
This PR adds missing rule exports for the following rules:

- directive-class-suffix
- no-forward-ref
- relative-url-prefix
- use-injectable-provided-in

Fixes #49

### CODE REVIEW

**Comment by JamesHenry** [comment]
@nzacca I'm sorry but build triggers for Azure DevOps do not seem to be working at all today. Nothing changed about the setup...

**Comment by JamesHenry** [comment]
I think I'll look into switching to github actions anyway, I've wanted an excuse to try them out

**Comment by nzacca** [comment]
Hmm... Is it possibly something I added that is causing the problem?

**Comment by nzacca** [comment]
As a test, did you try explicitly setting a trigger for PRs like the following? It should have picked up as it is currently setup though.

```yaml
trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master
```

**Comment by JamesHenry** [comment]
I've switched over to github actions, was super easy they've done a great job with them

**Comment by JamesHenry** [comment]
Thanks again! Published as v0.0.1-alpha.22

**Comment by BO41** [comment]
using version 22, I still get
```
  1:1   error    Definition for rule '@angular-eslint/directive-class-suffix' was not found      @angular-eslint/directive-class-suffix
  1:1   error    Definition for rule '@angular-eslint/use-injectable-provided-in' was not found  @angular-eslint/use-injectable-provided-in
  1:1   error    Definition for rule '@angular-eslint/no-forward-ref' was not found              @angular-eslint/no-forward-ref
  1:1   error    Definition for rule '@angular-eslint/relative-url-prefix' was not found         @angular-eslint/relative-url-prefix
```

**Comment by JamesHenry** [comment]
@BO41 please check `0.0.1-alpha.23` which I just published, should hopefully be fixed as I did a fresh build on latest master

**Comment by BO41** [comment]
v23 did fix the issue :+1:

**Pull request merged**
