### PR TITLE
fix(eslint-plugin-template): [no-call-expression] False negative with the new control flow syntax

### LINKED ISSUE #1672: [no-call-expression] False negative with the new control flow syntax
**Description and reproduction of the issue**

```JSON
{
  "rules": {
    "@angular-eslint/template/no-call-expression": "error"
  }
}
```

`no-call-expression` should trigger when calling a function with the new control flow syntax, but it isn't.

```HTML
<!-- does not trigger, but it should -->
@if (shouldRender()) {
  <div>testing</div>
}

<!-- triggers correctly -->
<div *ngIf="shouldRender()">testing</div>
<!--        ~~~~~~~~~~~~~~ -->
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `17.1.1` |
| `@angular-eslint/template-parser`         | `17.1.1` |
| `@typescript-eslint/parser`               | `6.13.2` |
| `ESLint`                                  | `8.48.0` |
| `node`                                    | `20.10.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.7
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router, ssr

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1700.7
@angular-devkit/build-angular        17.0.7
@angular-devkit/core                 17.0.7
@angular-devkit/schematics           17.0.7
@angular/cdk                         17.0.4
@angular/material                    17.0.4
@angular/material-date-fns-adapter   17.0.4
@schematics/angular                  17.0.7
rxjs                                 7.8.1
typescript                           5.2.2
webpack                              5.89.0
zone.js                              0.14.2
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

### PR DESCRIPTION
**Pull request by Res42**
Closes #1672

The basic solution was to add more KEYS special cases for `preprocessNode`.

`prefetchTriggers` and `triggers` are simple object dictionaries in `@defer`s AST so I also added `Object: ['when']` to the KEYS.

---

I'll include some ASTs below:

### @if

```html
@if (testing1()) {
  <div [id]="testing3()"></div>
} @else if (testing2()) {
  <div [id]="testing4()"></div>
} @else {
  <div [id]="testing5()"></div>
}
```

Generated AST:

```js
{
  type: 'IfBlock',
  branches: [
    {
      type: 'IfBlockBranch',
      children: [/* ... */], // need to preprocess this too
      expression:  {
        // testing1()
        /* MISSING */ type: 'ASTWithSource',
        ast: {
          // This is the match for the rule
          /* MISSING */ type: 'Call'
        }
      }
    },
    {
      type: 'IfBlockBranch',
      children: [/* ... */], // need to preprocess this too
      expression:  {
        // testing2()
        /* MISSING */ type: 'ASTWithSource',
        ast: {
          // This is the match for the rule
          /* MISSING */ type: 'Call'
        }
      }
    },
    {
      type: 'IfBlockBranch',
      children: [/* ... */], // need to preprocess this too
      expression:  null
    }
  ]
}
```

> Note that the `@else` block is represented with an `'IfBlockBranch'` with `expression: null` so the code should skip missing `KEY` properties in the `preprocessNode`.

### @switch

```html
@switch (testing1()) {
  @case(testing2()) {
    <div [id]="testing3()"></div>
  }
  @default {
    <div [id]="testing4()"></div>
  }
}
```

Generated AST:

```js
{
  type: 'SwitchBlock',
  expression:  {
    // testing1()
    /* MISSING */ type: 'ASTWithSource',
    ast: {
      // This is the match for the rule
      /* MISSING */ type: 'Call'
    }
  },
  cases: [
    {
      type: 'SwitchBlockCase',
      children: [/* ... */], // need to preprocess this too
      expression:  {
        // testing2()
        /* MISSING */ type: 'ASTWithSource',
        ast: {
          // This is the match for the rule
          /* MISSING */ type: 'Call'
        }
      }
    },
    {
      type: 'SwitchBlockCase',
      children: [/* ... */], // need to preprocess this too
      expression:  null
    }
  ]
}
```

> Note that the `@default` block is represented with an `'SwitchBlockCase'` with `expression: null` so the code should skip missing `KEY` properties in the `preprocessNode` here too.

### @for

```html
@for (test of testing1(); track test.testing2()) {
  <div [id]="testing3()"></div>
} @empty {
  <div [id]="testing4()"></div>
}
```

Generated AST:

```js
{
  type: 'ForLoopBlock',
  children: [/* ... */], // need to preprocess this too
  empty: {
    children: [/* ... */], // need to preprocess this too
    /* MISSING */ type: 'ForLoopBlockEmpty'
  },
  expression: {
    // testing1()
    /* MISSING */ type: 'ASTWithSource',
    ast: {
      // This is the match for the rule
      /* MISSING */ type: 'Call'
    }
  },
  trackBy: {
    // test.testing2()
    /* MISSING */type: 'ASTWithSource',
    ast: {
      // This is the match for the rule
      /* MISSING */ type: 'Call'
    }
  }
}
```

> Note that the `@empty` block can be omitted, so the `empty` property can be `null` so the code should skip missing `KEY` properties in the `preprocessNode` here too.

### @defer

As I see it work has already been done with `DeferredBlock` so just some modifications are needed.

Basic usage:

```html
@defer {
  <div [id]="testing1()"></div>
} @error {
  <div [id]="testing2()"></div>
} @loading {
  <div [id]="testing3()"></div>
} @placeholder {
  <div [id]="testing4()"></div>
}
```

```js
{
  type: 'DeferredBlock',
  children: [/* ... */], // need to preprocess this too
  error: {
    // need to preprocess this too
    children: [/* ... */], // need to preprocess this too
  },
  loading: {
    // need to preprocess this too
    children: [/* ... */], // need to preprocess this too
  },
  placeholder:{
    // need to preprocess this too
    children: [/* ... */], // need to preprocess this too
  },
  prefetchTriggers: {},
  triggers: {}
}
```

The rule should not error on `viewport(ref)` and other configs that seems like function calls but are built-ins.

```html
@defer (on viewport(ref)) {
  <div [id]="testing()"></div>
}
```

Generated AST:

```js
{
  type: 'DeferredBlock',
  children: [/* ... */], // need to preprocess this too
  error: null,
  loading: null,
  placeholder: null,
  prefetchTriggers: {},
  triggers: {
    viewport: {
      // no need to do anything here
      /* ... */
    }
  }
}
```

But it should error on `when` and `prefetch when`.

```html
@defer (when testing1(); prefetch when testing2()) {
  <div [id]="testing2()"></div>
}
```

Generated AST:

```js
{
  type: 'DeferredBlock',
  children: [/* ... */], // need to preprocess this too
  error: null,
  loading: null,
  placeholder: null,
  prefetchTriggers: {
    when: {
      /* MISSING */ type: 'BoundDeferredTrigger',
      value: {
        // testing2()
        /* MISSING */ type: 'Call'
      }
    }
  },
  triggers: {
    when: {
      /* MISSING */ type: 'BoundDeferredTrigger',
      value: {
        // testing1()
        /* MISSING */ type: 'Call'
      }
    }
  }
}
```

> Note that the `@error`, `@loading`, `@placeholder` blocks can be omitted, so the `empty`, `loading`, `placeholder` properties can be `null` so the code should skip missing `KEY` properties in the `preprocessNode` here too.

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thank you @Res42 I'm afraid I processed PRs in order, and so an existing PR that was just merged overlapped with this a lot #1656 

Please can you reconcile your work against it and see what still needs to be updated/added?

**Review by JamesHenry — CHANGES_REQUESTED** [review]
See comment above

**Comment by Res42** [comment]
Done.

**Review by JamesHenry — APPROVED** [review]
Thank you @Res42!

**Pull request merged**
