### PR TITLE
feat(i18n): include i18n-* with the require description rule

### PR DESCRIPTION
**Pull request by smithpb**
This pull request is to expand on the existing rule to require a description on the i18n attribute. With these changes, the i18n-* will also require a description.

### CODE REVIEW

**Comment by alex-okrushko** [comment]
Overall looks good. The only concern that I have is that we are getting into a 3-rd level of `if` nesting. Anything we can do about that?

**Comment by smithpb** [comment]
With the nature of the types of checks being performed, refactoring to consolidate if-statements I feel would make things needlessly complicated and difficult to read.

**Comment by smithpb** [comment]
@JamesHenry I'm submitting a PR to hopefully get merged. Thanks.

**Review by JamesHenry — APPROVED** [review]
Thank you @smithpb!

**Review by JamesHenry — CHANGES_REQUESTED** [review]
Sorry, actually looks like a docs regen is needed:

```sh
yarn update-rule-docs
```

and commit the result

**Comment by JamesHenry** [comment]
Thanks again @smithpb - just FYI I updated the PR title (and squash commit) to better reflect the scope and change here

**Pull request merged**
