### PR TITLE
feat(eslint-plugin-template): add no-call-expression rule

### PR DESCRIPTION
**Pull request by paulotokimatu**

### CODE REVIEW

**Comment by paulotokimatu** [comment]
@JamesHenry I am having an issue regarding the start position of a method call.

If I have a template with:
```
<div>{{ getInfo1() }}</div>
```

I get the correct position:
`1:9  error  Avoid calling expressions in templates  @angular-eslint/template/no-call-expression`

But if the interpolation is on a new line, like:
```
<div>
  {{ getInfo2() }}
</div>
```

I get:
`2:7  error  Avoid calling expressions in templates  @angular-eslint/template/no-call-expression`

But it should actually be `2:6`, right? Can you point me where can I investigate that?

**Comment by paulotokimatu** [comment]
@JamesHenry Ping 😄

**Comment by JamesHenry** [comment]
Have you attempted to see what the underlying angular compiler thinks? It's possible this is just how it is currently applying the range/node information...

**Comment by paulotokimatu** [comment]
> 
> 
> Have you attempted to see what the underlying angular compiler thinks? It's possible this is just how it is currently applying the range/node information...

Yeah you are right, looks like it is just the way it comes from Angular compiler's `parseTemplate` method.

**Comment by JamesHenry** [comment]
Cool, @paulotokimatu would you like to take it up with the Angular team, or press ahead with the PR for now?

**Comment by paulotokimatu** [comment]
> 
> 
> Cool, @paulotokimatu would you like to take it up with the Angular team, or press ahead with the PR for now?

I will try taking a better look at that later, but anyway that would be outside the scope of this PR, so we can go ahead I guess. 😄

**Comment by JamesHenry** [comment]
Thanks!

**Pull request merged**
