### PR TITLE
docs(readme): add initial content to Rules List

### LINKED ISSUE #41: Rules List
Hello!

Is the Rules List still needed or is anyone working on this already? If not, I'd like to offer some assistance starting this as per the README: https://github.com/angular-eslint/angular-eslint#rules-list

### PR DESCRIPTION
**Pull request by nzacca**
Fixes #41 

Please let me know if I've missed anything. I wasn't sure of the best place to put this so I mirrored the typescript-eslint project. Happy to make any adjustments as needed.

I marked the rules I saw with PRs as WIP. Let me know if there's something else you'd like to track on this page.

### CODE REVIEW

**Comment by JamesHenry** [comment]
As this project is so new and people will come wondering about the status, could we instead embed this directly in the main README for now?

I think it might be best to remove the "has integration test" comment as it might give false confidence. The rules in question happen to be included in an Angular CLI integration test and the focus is just that - checking that angular-eslint is functional with the Angular CLI. In the integration test I have not sought to provide valuable tests at a rule level, they should be covered by the unit tests

**Comment by JamesHenry** [comment]
And thank you very much for putting this together

**Comment by JamesHenry** [comment]
PS I just merged the PR for `no-input-rename`

**Comment by JamesHenry** [comment]
Also merged the PR for `template/no-negated-async`

**Comment by JamesHenry** [comment]
You may actually want to look into how we generate rules lists programatically over in https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin

Don't need to worry about lots of different columns for now, we can evolve it over time!

**Comment by nzacca** [comment]
@JamesHenry Thank you so much for directing me to the programmatic solution. I was hoping there would be one. I will make the changes as you have outlined:

- Move list to README
- Remove integration tests column
- Look into programmatic generation of the list using [this as a guide](https://github.com/typescript-eslint/typescript-eslint/blob/367b18f0187ee503c4b21444864027f389a0c69a/packages/eslint-plugin/tools/generate-rules-lists.ts)

**Comment by nzacca** [comment]
@JamesHenry Is it ok to add support for ts-node in the dev dependencies or would you prefer that I write the script with javascript instead? If adding ts-node, should I mimic adding ts-node to the root or would you prefer that it was added to the eslint-plugin package only?

**Comment by JamesHenry** [comment]
Thanks, Nicholas - adding ts-node to the root would be great

**Comment by nzacca** [comment]
@JamesHenry Ah! I just missed your message. I will add ts-node to the root instead. The generator script has been completed. I will move the script to the root package.json as well.

**Comment by nzacca** [comment]
@JamesHenry 

This is ready for another look.

Thank you!

**Comment by BO41** [comment]
Shouldn't all `template-*` rules be checked?
At least [`banana-in-a-box`](https://github.com/angular-eslint/angular-eslint/commit/6295af7258fc3b24fa2c405785d9dcabfe8230ec#diff-c4d7075d75585cacb906305ad07b4442R199)?

**Comment by JamesHenry** [comment]
Yes currently the template plugin is missing from this PR (there are two rules in there right now, the two that the Angular CLI enables by default and thus highest priority ones)

**Comment by nzacca** [comment]
Sorry about that. I will add the template plugin into the script.

**Comment by nzacca** [comment]
@BO41 @JamesHenry 

Currently the template rule name for `banana-in-a-box` differs from the codelyzer name `template-banana-in-box`. I first tried to parse by simply adding the `template-` prefix to perform a match but we're still off by the `-a-` in the new name.

I can proceed by either providing a manual map or we can rename the rules to match. Open to other suggestions. I will check to see if there are other mismatches for the non-template rules.

Also, is there another spot I should be checking for the template rules? I only see the 2 that James mentioned in the template package (one of which is not in the index which we're using here to map the list of finished rules). Let me know and I can adjust as needed.

Thank you!

**Comment by nzacca** [comment]
`use-injectable-provided-in` and `relative-url-prefix` are missing from the `index.ts` in `eslint-plugin`. Not sure if these were left out on purpose. `no-negated-async` is also missing from the template index.

I can open another PR to add those if it is okay to add.

**Comment by nzacca** [comment]
I have added support for the template plugin and manually mapped the `banana-in-a-box` rule for now. I've added a check to map rule names based on:

- exact match
- manual map (ex. if a rule name changes completely)
- with a `template-` prefix

Let me know your thoughts. Happy to make any additional changes.

**Comment by nzacca** [comment]
@JamesHenry My pleasure. Thanks for pushing this project forward!

The missing no-negated-async issue was due to this: https://github.com/angular-eslint/angular-eslint/pull/46

We're actually missing a couple others that I mentioned above here: https://github.com/angular-eslint/angular-eslint/pull/43#issuecomment-590228061

As requested, I will look into integrating this process into the dev workflow. I'll take a look when I finish work today.

**Comment by nzacca** [comment]
@JamesHenry 

Changes complete. Devs will be prompted with the following error message on push (similar to the formatting check) if the README is out of date.

```
yarn run v1.22.0
$ yarn check-readme && yarn format-check
$ yarn exec-tool check-readme
$ ts-node --files --transpile-only --project tsconfig.tools.json -r tsconfig-paths/register tools/scripts/exec-tool.ts check-readme
Please update the README before pushing: `yarn update-readme`.
error Command failed with exit code 1.
```

I added support for alias paths in this last commit as well. I hope that was ok. I didn't like using the relative paths. I can move that so that it is supported across the whole project if you'd like but probably better to do that in another PR.

I also noticed the Codecov report. Do we need specs for these scripts?

Let me know your thoughts and, as always, happy to make any additional changes.

Cheers!

**Comment by nzacca** [comment]
@JamesHenry My pleasure!

If there are any changes you'd like me to do, major or minor, please do let me know. I'm happy to help.

Moreover, if there are Rules I can help with, I wouldn't mind trying my hand at one. I've never built a Rule before but if there's one you think would be a `good-first-issue`, I'd like to try.

**Comment by JamesHenry** [comment]
Feel free to take any of them on, I haven't categorised them in any way I'm afraid. There should be a good amount of copy and paste based inspiration there already and you can let me know if you get stuck on a particular rule.

May I suggest creating an issue about the rule if you want to grab it and then others will know you are working on it

**Comment by JamesHenry** [comment]
^ @nzacca

**Comment by nzacca** [comment]
Thanks @JamesHenry ! I will give it a go and let you know if I run into any issues. I appreciate your guidance.

**Pull request merged**
