### PR TITLE
feat(eslint-plugin-template): [attributes-order] add rule

### LINKED ISSUE #127: Rule proposal: template/attributes-order
It makes sense for structural directives like `*ngIf` to be first in the list of attributes:
```
<div [ngClass]="item.classes" my-decorator *ngIf="item.isVisible" [my-decorator-extras]="item.extras">
  {{ item.text | translate }}
</div>
```

I don't promise anything, but if I have the time, I'll look into it this month.

P.S. Some issue templates could be useful. I'll also look into this.

P.S.2 Thanks for all the hard work!

### PR DESCRIPTION
**Pull request by nickbullock**
closes #127 

State: rule and tests are ready, fixer is not ready.
Let's discuss default order here.

### CODE REVIEW

**Review by rafaelss95 — COMMENTED** [review]
Thanks again for taking this, @nickbullock! 🚀 

I know it's still a draft, but I went ahead and left some comments (let me know your opinions on this).

I didn't comment about the sorting part, because I know it'll going to change with the `alphabetical` option + fix.

**Comment by DaSchTour** [comment]
Can somebody pick this up and continue on this? It would be really great to have this lint rule published.

**Comment by JamesHenry** [comment]
@nickbullock please could you provide an update on how you would like to proceed on this PR?

**Comment by JamesHenry** [comment]
Given it's been nearly a year since a response was received from the original author I am going to close this PR so that it is clear that it is available for other community members to work on.

If @DaSchTour or anyone else who would like this rule would like to work on it please feel free to open a fresh PR!

**Comment by lachieh** [comment]
@rafaelss95 @JamesHenry Any updates? Looks like there is a new PR available. Would be great to get this rule in.

**Pull request closed without merging**
