### PR TITLE
docs(readme): Usage without Angular CLI Builder

### PR DESCRIPTION
**Pull request by qkevinto**
Addresses #79

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thanks for this @qkevinto, I have carved out some time this weekend to work on angular-eslint so I'll be looking into this then!

**Comment by JamesHenry** [comment]
Apologies (in particular to the tagged folks and) if you are subscribed to multiple issues/PRs you will see this copy pasted multiple times:

---

I have been going through a difficult time personally dealing with, amongst other things, the sudden death of my Dad. Open-source contributions have naturally had to take a back seat.

I really appreciate your continued patience on this and I will be doing my best to improve the speed at which PRs are merged in the near future. Hopefully this will then also allow more core contributors/maintainers to emerge from the community to work alongside @mgechev @wKoza @sfabriece @rafaelss95 and myself.

Thanks again for giving this project and the community your time and contribution.

**Comment by mgechev** [comment]
Thanks for the PR!

**Comment by JamesHenry** [comment]
Thanks again @qkevinto!

**Pull request merged**
