### PR TITLE
Include install instructions

### PR DESCRIPTION
**Pull request by BO41**
is this the correct way of including angular-eslint?

### CODE REVIEW

**Comment by BO41** [comment]
currently it is not possible to use `angular-eslint` with `typescript-eslint` (with required type checking), right?
Otherwise it would be good if it was documented as well

**Comment by JamesHenry** [comment]
Thanks a lot for this, I’ll take a look this weekend!

**Comment by JamesHenry** [comment]
Thanks again @BO41!

Check out the new Angular CLI integration test for how things are setup and configured in a way that matches the existing TSLint setup.

> currently it is not possible to use angular-eslint with typescript-eslint (with required type checking), right?

You can see how the two projects are used together in that integration test - you absolutely do want and need to use them together, angular-eslint builds on top of typescript-eslint and couldn't exist without it.

**Comment by BO41** [comment]
awesome, will take a look at it.
Thanks :)

**Pull request closed without merging**
