### PR TITLE
feat(eslint-plugin-template): possible new template-i18n rule

### PR DESCRIPTION
**Pull request by LakMoore**
inspiration from Codelyzer, re-written for es-lint

Have done my best to follow your banana-in-a-box template rule and created an i18n rule, which I quite liked from Codelyzer.  Have made a few tweaks (dare I say improvements?).

Let me know if you want anything changed. (I'm not very experienced at writing tests, but these do pass and the rule functions nicely on my own codebase)

Cheers

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thanks for this @LakMoore, I have carved out some time this weekend to work on angular-eslint so I'll be looking into this then!

**Comment by JamesHenry** [comment]
Apologies (in particular to the tagged folks and) if you are subscribed to multiple issues/PRs you will see this copy pasted multiple times:

---

I have been going through a difficult time personally dealing with, amongst other things, the sudden death of my Dad. Open-source contributions have naturally had to take a back seat.

I really appreciate your continued patience on this and I will be doing my best to improve the speed at which PRs are merged in the near future. Hopefully this will then also allow more core contributors/maintainers to emerge from the community to work alongside @mgechev @wKoza @sfabriece @rafaelss95 and myself.

Thanks again for giving this project and the community your time and contribution.

**Comment by mgechev** [comment]
I'll let @wKoza @sfabriece @rafaelss95 look into this.

**Comment by casoetan** [comment]
@LakMoore great job. Hey guys what's holding this back? Is it the test? I can help out if needed.

**Comment by JamesHenry** [comment]
I am going to close this as it's been quite a long time without hearing from the original author (no judgement, it happens) and I want to open it up to other members of the community like @casoetan to take forward if they care about it.

**Pull request closed without merging**
