### PR TITLE
fix(eslint-plugin-template): handle optional fix prop in postprocessor, fixed preprocessor return type

### PR DESCRIPTION
**Pull request by AlexanderFSP**
Resolve https://github.com/angular-eslint/angular-eslint/issues/151

### CODE REVIEW

**Review by JamesHenry — CHANGES_REQUESTED** [review]
Please revert all the unnecessary renaming of things in the tests, it has made things less easy to scan and know what is coming from the current test case vs what is a fixed variable, and just in general it's not great for reviewing PRs to change more than is in scope

**Comment by JamesHenry** [comment]
Sorry for not being clear - you made some functional changes around using a consistent interface for what we return for the processor, that was fine, and did require a small change to the tests, but you can had renamed and refactored a load of other parts of the test code which were not required to get them to pass. It was the latter point I was requesting to revert, not the entire thing.

If you want to bring that change back (without the refactoring) that's absolutely fine, just let me know either way how you wish to proceed with this PR

**Comment by AlexanderFSP** [comment]
> Sorry for not being clear - you made some functional changes around using a consistent interface for what we return for the processor, that was fine, and did require a small change to the tests, but you can had renamed and refactored a load of other parts of the test code which were not required to get them to pass. It was the latter point I was requesting to revert, not the entire thing.
> 
> If you want to bring that change back (without the refactoring) that's absolutely fine, just let me know either way how you wish to proceed with this PR

So, I've rolled back changes for `preprocessor`, carefully fixed tests & added basic tests to cover at least first if statement in `postprocessor`. To cover the rest functionality - I think refactoring also needed because there is no possibility to mock `rangeData` Map in an easy way...

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
Great, thanks!

**Pull request merged**
