### PR TITLE
fix(template-parser): add BindingPipe exp to VisitorKeys (#337)

### PR DESCRIPTION
**Pull request by detljh**
Added `BindingPipe: ['exp']` to `template-parser` for (#337)

### CODE REVIEW

**Review by JamesHenry — CHANGES_REQUESTED** [review]
Thanks! Please also add some relevant test coverage in the template plugin which captures the source you initially discovered this issue on

**Comment by detljh** [comment]
Sorry I'm not sure where I would add relevant tests

**Comment by JamesHenry** [comment]
@detljh You reference tests from this repo in your original bug report - I'm simply referring to have an example of what was missing before and how you originally found this

**Comment by detljh** [comment]
Oh in my original bug report those tests weren't from this repo. I found the bug while creating tests for a rule I wrote

**Comment by JamesHenry** [comment]
@detljh Ah ok, well yeah I think we currently don't have anything in this repo which is affected by this, but I agree it makes sense to have, so I'm going to merge it

**Pull request merged**
