### PR TITLE
fix(eslint-plugin): fix placement of lifecycle interface for subclasses

### PR DESCRIPTION
**Pull request by al-mart**

### CODE REVIEW

**Comment by al-mart** [comment]
https://github.com/angular-eslint/angular-eslint/issues/1901

**Review by JamesHenry — CHANGES_REQUESTED** [review]
@al-mart Yes please take a look at existing rules, there are many cases where auto fixing is tested.

`convertAnnotatedSourceToFailureCase()` is out utility to allow for a nice visual way to write assertions about errors.

`annotatedSource` is with the errors, `annotatedOutput` is after the fixes are applied

**Comment by al-mart** [comment]
Thank you. Will add the missing test cases accordingly.

**Comment by JamesHenry** [comment]
@al-mart Following up on this one please

**Comment by al-mart** [comment]
Yeah, sorry was on vacation without the pc. Will add the PR with tests tomorrow.

**Comment by al-mart** [comment]
@JamesHenry added the missing test case, the problem is only occurring when there is a class extension but no interfaces at all.

**Comment by JamesHenry** [comment]
@al-mart I have updated the branch, will you be addressing the CI failures please?

**Comment by JamesHenry** [comment]
@al-mart I fixed things up for you, thanks again for the PR

**Pull request merged**
