### PR TITLE
feat(builder): add option to produce output file

### PR DESCRIPTION
**Pull request by mrmeku**
Sometimes (typically during CI) user's want to log an output file to disk with their lint results for consumption in a downstream system (like SonarQube as one example). In theory this could be accomplished by piping STDOUT to a file, but currently this builder logs some other helpful comments in addition to the formatted result so some parsing would be required is a user wanted to extract a JSON or XML formatted report.

I've mirrored the API eslint has for producing an output file: https://eslint.org/docs/user-guide/command-line-interface#output

### CODE REVIEW

**Comment by mrmeku** [comment]
Hi James! Long time no see :)

As one of my last acts as a Narwhalian I'm trying to fix up this issue I just filed: https://github.com/nrwl/nx/issues/2435

Hence the PR. Let me know if you want changes to it. I made the decision to merge all the coverage reports into one big report for the sake of writing the output file to disk. This does slightly change what is written to STDOUT since before the number of errors / warnings were written on a per file basis. After the change they are written once for the entire lint job.

If you'd prefer to keep the old logging behavior let me know!

**Comment by JamesHenry** [comment]
Hey Dan!

> my last acts as a Narwhalian

Best of luck in your next adventure, wherever it may be. DM me on twitter?

Because @rarmatei was linking things I have found that Nrwl is copying this code over into a new package, which seems... odd.

Why don't we all chat?

**Comment by rarmatei** [comment]
> Hey Dan!
> 
> > my last acts as a Narwhalian
> 
> Best of luck in your next adventure, wherever it may be. DM me on twitter?
> 
> Because @rarmatei was linking things I have found that Nrwl is copying this code over into a new package, which seems... odd.
> 
> Why don't we all chat?

Hey James! The communication issue is 100% on me and I'm really sorry for that. The PR is open, not merged, and I am genuinely happy it will pass through your input as well.

Victor will get in touch with you to discuss this. Part of my PR was to add more unit and e2e tests (most of it is composed of that actually). So depending on what you and Victor decide, I'd be happy to duplicate or move them on to this repo as well, if you think it'd be useful.

**Comment by JamesHenry** [comment]
Thanks @rarmatei, I'll chat with Victor :)

**Comment by JamesHenry** [comment]
Hey Dan, given we decided to press ahead with the Nrwl owned builder for Nx use-cases I am going to close this one for now and keep it aligned with the default Angular CLI TSLint builder.

Again all the best with whatever comes next for you, and DM me on twitter to let me know :P

**Pull request closed without merging**
