### PR TITLE
docs: add supported rules in README

### PR DESCRIPTION
**Pull request by jfgreffier**
Hi !

Here's a PR to add the list of rules in @angular-eslint/eslint-plugin README.md
It takes the description from the rules sources and links to the individual rule doc, similarly to typescript-eslint.

### CODE REVIEW

**Comment by rafaelss95** [comment]
My 2 cents: while I do think it's a good idea, I think it's better if we create a script to do it automatically in order to keep it always up-to-date.

**Comment by jfgreffier** [comment]
Should I create an issue for a script to extract automatically rules and create a summary ?

Will this PR be closed ? Or actually reviewed ?

Halp

**Comment by jfgreffier** [comment]
@JamesHenry is working on a solution to generate doc automatically ? https://github.com/angular-eslint/angular-eslint/pull/507#issuecomment-848048082

**Comment by JamesHenry** [comment]
@jfgreffier I think we'll close this one for now too, instead I will update the main README to highlight the fact that the individual rules docs now exist as part of a broader updated I will be making to the file.

Thanks again for contributing!

**Pull request closed without merging**
