### PR TITLE
fix(eslint-plugin-template): [prefer-self-closing-tags] consider ng-content and ng-template elements

### LINKED ISSUE #1567: [@angular-eslint/template/prefer-self-closing-tags] `ng-content` should be marked as self-closing tag
Hey 👋

Thanks for your great work!

I recently started using the `prefer-self-closing-tags` rule in a project, and noticed that the `ng-content` element was not marked as error when using the "full" syntax.

**Description and reproduction of the issue**

```JSON
{
  "rules": {
    "@angular-eslint/template/prefer-self-closing-tags": ["error"]
  }
}
```

```HTML
// your repro code case

<!-- Should be marked as error -->
<ng-content></ng-content>

<!-- Correctly marked as error -->
<ng-container></ng-container>

<!-- Correctly marked as error -->
<router-outlet></router-outlet>
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `16.2.0` |
| `@angular-eslint/template-parser`         | `16.2.0` |
| `@typescript-eslint/parser`               | `5.62.0` |
| `ESLint`                                  | `8.46.0` |
| `node`                                    | `18.16.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 16.2.9
Node: 18.16.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.9
@angular-devkit/build-angular   16.2.9
@angular-devkit/core            16.2.9
@angular-devkit/schematics      16.2.9
@angular/cli                    16.2.9
@schematics/angular             16.2.9
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

### PR DESCRIPTION
**Pull request by json-derulo**
Currently the prefer-self-closing-tags rule doesn't report errors on  empty `<ng-content></ng-content>` and `<ng-template></ng-template>` elements, which is fixed by this pull request.

Closes #1567

### CODE REVIEW

**Comment by JamesHenry** [comment]
That's because this didn't used to be supported in Angular:

image

I don't know when they stopped throwing the above parse error for these but happy to learn that they did.

**Comment by JamesHenry** [comment]
Thanks @json-derulo I've added this to the v17 branch just in case this change in behaviour is particularly disruptive for larger codebases

**Comment by JamesHenry** [comment]
@json-derulo I'm afraid I've had to revert for the two plugins, it causes compilation issues with typescript-eslint v6

**Comment by json-derulo** [comment]
@JamesHenry Could you explain in more detail what the problem with typescript-eslint v6 is? I checked out the `next-major-release/v17` branch (which still includes my commit) and after installing the dependencies, I ran lint, test & build. Everything seems to work fine for me.

**Comment by JamesHenry** [comment]
It includes your commit but then the aforementioned revert to the plugin by me: https://github.com/angular-eslint/angular-eslint/pull/1563/commits/2498238ac64caaa539ac9d165157c6c4c937e747

The issue is https://github.com/typescript-eslint/typescript-eslint/issues/7605

**Pull request merged**
