### PR TITLE
feat(eslint-plugin-template): no-negated-async (with location issues)

### PR DESCRIPTION
**Pull request by JamesHenry**
Opening for visibility only right now.

@mgechev Do you know if there is any information/spec anywhere for how location information is applied to Angular Template AST nodes?

I have made progress on the `no-negated-async` rule here, but it's all through trial and error and I'm not very happy with it.

The use, and logic, of `sourceSpan` and `span` appears to be hard to predict, and inconsistent depending on hierarchies within the template.

E.g. the location data for a an async `BindingPipe` seems to change how it is given depending on whether or not an `Element` exists within its ancestors...

Please let me know if there are any resources in this area, or if I missed some existing utilities in the codelyzer codebase that could help with this!

### CODE REVIEW

**Comment by mgechev** [comment]
@ayazhafiz is the last one who worked on this. I believe he mentioned some improvements are coming. Ayaz, would you share the status if you're aware of it?

**Comment by ayazhafiz** [comment]
I have a PR that should resolve all inconsistencies with the AST at angular/angular#31897. We are waiting on a review from the compiler code owner, so it is difficult for me to predict when this will land.

I'm sorry for the issues you've had with this @JamesHenry. There is a longer discussion of the kind of issues present with the Angular ASTs at angular/angular#31898 that may give you more information about how the AST works. Fingers crossed this gets moving again soon.

**Comment by JamesHenry** [comment]
Ah thanks @ayazhafiz! Is there anything blocking your PR that you know of?

**Comment by ayazhafiz** [comment]
I don't think anything should be blocking the PR. The code owner is Alex Rickabaugh (@alxhub). The Angular team has been really busy, but we'll probably have some movement on this in the near future.

**Comment by mgechev** [comment]
I'll check with Alex on AngularConnect next week :)

**Comment by JamesHenry** [comment]
@mgechev See you there! 🙌

**Comment by JamesHenry** [comment]
FYI Alex R and I chatted briefly at Angular Connect about this, and we are going to be following up together this week

**Comment by JamesHenry** [comment]
@ayazhafiz main PR was merged so I can pick this up again this week!

**Comment by ayazhafiz** [comment]
@JamesHenry cool! You should be able to get the location of an expression like `async` in a template with the [`sourceSpan` field](https://github.com/angular/angular/blob/1d429b216556911edc4b0675ece4cb9081967155/packages/compiler/src/expression_parser/ast.ts#L30-L33). If there are still issues with whitespace, you may have to reparse templates with whitespace preserved for now.

**Pull request merged**
