### PR TITLE
fix(eslint-plugin): update list of native events

### PR DESCRIPTION
**Pull request by demkalkov**
Update a list of native events.
Resolves issue #1671

### CODE REVIEW

**Comment by JamesHenry** [comment]
@demkalkov Please can you cite the source for this hugely updated list?

The original comment by Rafael from several years ago does not seem to contain a straightforward list? It would definitely be good to make it clear where this data comes from

**Review by JamesHenry — CHANGES_REQUESTED** [review]
See comment

**Comment by demkalkov** [comment]
> @demkalkov Please can you cite the source for this hugely updated list?
> 
> The original comment by Rafael from several years ago does not seem to contain a straightforward list? It would definitely be good to make it clear where this data comes from

The list of events is taken from the MDN page specified in a file, but a French version of it. I've just started to update the English version, but it might take some time.

**Comment by demkalkov** [comment]
> See comment

done

**Comment by JamesHenry** [comment]
Looks like this change causes the unit tests to fail, did you run them locally?

**Comment by JamesHenry** [comment]
@demkalkov Following up on this one please

**Comment by demkalkov** [comment]
> @demkalkov Following up on this one please

updated and fixed the unit tests

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
Thank you @demkalkov

**Pull request merged**
