### PR TITLE
fix(eslint-plugin-template): [prefer-self-closing-tags] always ignore index.html files

### PR DESCRIPTION
**Pull request by Squixx**
Ignores index.html files for prefer-self-closing-tags  as described in #1857

### CODE REVIEW

**Review by JamesHenry — CHANGES_REQUESTED** [review]
You should be able to add a unit test for this by setting `filename` please

**Comment by Squixx** [comment]
added!

**Comment by JamesHenry** [comment]
Test looks good, please run `yarn update-rule-docs` and commit the result, the docs are generated from the unit tests so whenever they change the docs need to too

**Comment by Squixx** [comment]
i've updated the docs. However currently the result doesn't make sense in this context. Is there a ways to simply annotate a rule output? e.g. `src/index.html` is excluded as this would prevent angular from bootstrapping

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
Thanks so much @Squixx!

**Comment by Squixx** [comment]
Thanks for guiding me through the repo.

**Comment by silvanadrian** [comment]
@JamesHenry Is there a plan on getting this fix released anytime soon?

**Comment by JamesHenry** [comment]
image

https://github.com/angular-eslint/angular-eslint?tab=readme-ov-file#package-versions

**Pull request merged**
